### ISSUE TITLE
Occurrences count

### ISSUE THREAD

**Issue by nestorjal** [gbif/occurrence#11]
We're starting to use the API to get some global and per dataset counts, I've found several incongruences between the number of occurrences available vs the ones showed in GBIF portal, therefore a different count in the country total  occurrences. The datasets are listed here:

| dataset                        | occurrences API | occurrences IPT | diff |
|--------------------------------|-----------------|-----------------|------------|
| http://doi.org/10.15472/vharp3 | 30852           | 14508           | -16344     |
| http://doi.org/10.15472/l7odt1 | 88177           | 75786           | -12391     |
| http://doi.org/10.15472/omyib6 | 27081           | 18252           | -8829      |
| http://doi.org/10.15468/3gcjmz | 15193           | 6663            | -8530      |
| http://doi.org/10.15472/ugl7c1 | 8721            | 839             | -7882      |
| http://doi.org/10.15472/hyvyhz | 11185           | 5600            | -5585      |
| http://doi.org/10.15472/esjdio | 85003           | 80000           | -5003      |
| http://doi.org/10.15472/xeyoxy | 5578            | 2789            | -2789      |
| http://doi.org/10.15468/7wco9u | 6818            | 4810            | -2008      |
| http://doi.org/10.15472/ea8sek | 370865          | 369837          | -1028      |
| http://doi.org/10.15472/dbowdj | 1658            | 829             | -829       |
| http://doi.org/10.15472/a5ffcg | 5575            | 5112            | -463       |
| http://doi.org/10.15472/1rhjvl | 653             | 327             | -326       |
| http://doi.org/10.15472/1vqsov | 30999           | 30769           | -230       |
| http://doi.org/10.15472/tnfgvi | 944             | 728             | -216       |
| http://doi.org/10.15472/zui9kc | 6817            | 6702            | -115       |
| http://doi.org/10.15472/j8284t | 107360          | 107293          | -67        |
| http://doi.org/10.15472/1zzafb | 10708           | 10702           | -6         |
| http://doi.org/10.15472/z2bip5 | 11900           | 11897           | -3         |
| http://doi.org/10.15468/pigtbt | 5363            | 5361            | -2         |
| http://doi.org/10.15472/timk5o | 5680            | 5679            | -1         |
| http://doi.org/10.15472/7oysm0 | 13561           | 13560           | -1         |
| http://doi.org/10.15472/g0tc1y | 591             | 590             | -1         |
| http://doi.org/10.15472/yklumo | 432             | 431             | -1         |
| http://doi.org/10.15472/cx638b | 145             | 144             | -1         |

**Comment by cgendreau** [comment]
Hi @nestorjal , we don't have automatic deletion setup for the moment.

**Comment by timrobertson100** [comment]
Thanks @nestorjal.  Because people often make mistakes in identifiers, we have not implemented an auto deletion function as they sometimes ask for this to be reverted.  We have pending work to change this policy though.

I have gone through the datasets and extracted the record keys to be removed from the index and are are attached.  I am afraid that they cannot be run for a couple of days while the new backbone taxonomy is being built but then we will pick this up.

In addition, we need to reindex the following and then addressed necessary deletions as they do not have the latest up to date content in the GBIF index, and the counts are all off.  This will also be picked up when the crawling is running again.
  http://doi.org/10.15472/xeyoxy
  http://doi.org/10.15472/zui9kc

Thanks for reporting these inconsistencies.

[br_del1.txt](https://github.com/gbif/occurrence/files/774492/br_del1.txt)

**Comment by nestorjal** [comment]
Thanks @cgendreau @timrobertson100, 

I asked to our principal publisher "IAvH" and they sometimes have to change the identifiers due to some requirements from the collections managers. 

It's nice to hear about the possible change in the policy, and as a content manager I'd like to promote the use of stable occurrenceIDs, if any experience from this side is helpful just let me know.

Thanks for your replies

**Comment by timrobertson100** [comment]
The deletions are now run, and the counts verified in the SOLR index.  The metrics on the dataset pages take up to an hour to update on GBIF.org.

These 2 datasets still require investigation by GBIF:
  http://doi.org/10.15472/xeyoxy
  http://doi.org/10.15472/zui9kc
