### ISSUE TITLE
Prevent a user from creating duplicate downloads

### ISSUE THREAD

**Issue by MattBlissett** [gbif/occurrence#184]
Some users, perhaps by mistake or while testing a script, generate multiple downloads with exactly the same filters.  These are often large downloads.

If a user already has a running download, and requests another, identical download (same format, same filter) the response could just return the download key of the original download.

**Comment by MattBlissett** [comment]
@timrobertson100 and others; what's a reasonable time for this? 12 hours?

There are a lot of repeated downloads made in short succession. The only use could be publishers checking before/after on small datasets (non-Hive downloads).

**Comment by sckott** [comment]
I've attempted to help reduce duplicated requests with this function in the R package  https://docs.ropensci.org/rgbif/reference/occ_download_cached.html - Though I don't know if people use it much. Is there any way to know if a newly generated dataset from a query would generate a different result than whats already cached on your servers - without actually processing the request?

**Comment by timrobertson100** [comment]
> @timrobertson100 and others; what's a reasonable time for this? 12 hours?

I could imagine someone publishing a dataset, downloading and reviewing the GBIF interpretation, applying changes republishing, repeat a couple of times. 12hrs would be a nuisance in that instance. Should we consider an exclusion if the filter is a single "datasetKey=..." or perhaps reduce that scenario to 1hr?

Otherwise, 12hrs seems reasonable, or perhaps something scaled to dataset size (1hr for <100k, 3hr <1M else 12hrs).

**Comment by MattBlissett** [comment]
This was implemented in March: 35 days for monthly downloads, and 4 hours for duplicate user downloads.
