### ISSUE TITLE
Add the calling agent to the occurrence-download table

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence#293]
It would be useful to be able to see if tools like rGBIF are used to issue the download that resulted in data being cited in a paper.

I suggest we add the calling agent (rGBIF, pyGBIF etc) and ideally the source (gbif.org or the hosted portal domain) to the occurrence download table. In the years to come, we'll be able to link from the cited paper, to the download to the calling agent to draw some metrics.

**Comment by bienflorencia** [comment]
Interesting! The possibility to track the data downloads that will come from our site is something that we would also be interested in having in our portal

**Comment by timrobertson100** [comment]
Thanks all.

We've done some of the preliminary work for this but haven't yet completed this task

**Comment by fmendezh** [comment]
as discussed with @MattBlissett and @marcos-lg this will require:
1. A new parameter and column _source_ 
2. Hosted portals  and GBIF Portals must pass a _source_ parameter (the domain name seems to be the best option) to the API backends @MortenHofft hosted portals and GBIF portal require some adjustments to implement this
3. If the _source_ parameter is absent, examine  the _User-Agent_ header and extract a know source from it (pyGbif, rGbif)
4. Adapt download statistics services to support the _source_ parameter

**Comment by MortenHofft** [comment]
Since downloads happen via GBIF.org, the most natural is for me to add `source` to a url parameter. Should I restrict the possible values somehow or accept that URL tampering the source is possible? I cannot quite figure out if it is worth the effort to restrict it. I cannot really see why anyone would be interested in tampering with those values.

**Comment by MattBlissett** [comment]
HPs can't control the user agent.

I suggest the link on https://www.gbif.us/data/?view=DOWNLOAD to https://www.gbif.org/occurrence/download/request?predicate=... becomes https://www.gbif.org/occurrence/download/request?predicate=...&source=gbif.us (as Morten wrote)

Portal16 would then need to pass that parameter on when making the download. That could be done like https://api.gbif-dev.org/v1/occurrence/download/request?source=gbif.us, or it could change the user agent. The user agent is less visible though, could it be forgotten if changes are made to HTTP libraries used in the portal etc?

**Comment by MortenHofft** [comment]
> HPs can't control the user agent. Maybe you can, I thought it was a security/privacy issue that browsers prevented this.

I do not believe I can. Most browsers and libraries do not allow it as far as I remember. But I can e.g. use the referer on the redirect to gbif.org and save it in a hidden form field if we want to mask it.

**Comment by MattBlissett** [comment]
I see the new `source` key on UAT, but should we exclude this from the API response? Or make it an admin-only feature?

**Comment by marcos-lg** [comment]
It's deployed to PROD but I still need to make the `source` field admin-only in the API. This will be deployed in the next days.

**Comment by marcos-lg** [comment]
Done

**Comment by camiplata** [comment]
Awesome! Thank you all.
So when we require the download metrics we only have to reach IT team right?

**Comment by marcos-lg** [comment]
We created an endpoint in the API to see these statistics and you can filter by source and dates, for example:

https://api.gbif.org/v1/occurrence/download/statistics/downloadsBySource?source=biodiversidad.co&fromDate=2023-01&toDate=2023-02

But we generate these statistics the first day of each month and it gathers the statistics in the previous case. In this example you can see already data for January 2023 but it's because we did it to test the deployment. So in February you will be able to see the full statistics for January. Anyway, if you need something more specific you can always ask us.

We'll also update the API documentation these days so that endpoint will appear here too https://www.gbif.org/developer/occurrence
