### ISSUE TITLE
API has JSON with unknown namespaces

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence#67]
From @rdmpage by email:

https://api.gbif.org/v1/occurrence/1802794471

Gives
```
eventTime: "03:39:59Z",
"http://unknown.org/http_//rs.gbif.org/terms/1.0/Multimedia": "[ {\n \"http://purl.org/dc/terms/rightsHolder\" : \"sharonn\",\n \"http://purl.org/dc/terms/references\" : \"https://www.inaturalist.org/photos/12798962\",\n \"http://purl.org/dc/terms/publisher\" : \"iNaturalist\",\n \"http://purl.org/dc/terms/type\" : \"StillImage\",\n \"http://purl.org/dc/terms/creator\" : \"sharonn\",\n \"http://purl.org/dc/terms/created\" : \"2018-01-09T03:39:59Z\",\n \"http://rs.tdwg.org/dwc/terms/catalogNumber\" : \"12798962\",\n \"http://purl.org/dc/terms/identifier\" : \"https://static.inaturalist.org/photos/12798962/original.jpg?1515484679\",\n \"http://purl.org/dc/terms/license\" : \"http://creativecommons.org/licenses/by-nc/4.0/\",\n \"http://purl.org/dc/terms/format\" : \"image/jpeg\"\n} ]",
identificationID: "20557412"
```

And https://api.gbif.org/v1/occurrence/1066474657 gives
```
country: "Australia",
"http://unknown.org/classs":
 "Insecta",
preparations: "Pin",
```

CC @mdoering (for info on namespaces) @aalbatross @fmendezh

**Comment by mdoering** [comment]
In haste, but somewhere a term got not parsed properly by the TermFactory.
In such cases when there is a term given with a simple name, not a URI, and that is not known to the factory (cause its not a dwc, gbif, etc term) it places it into the unknown.org domain. That was sth we always wanted to revisit, but ignoring the exact domain the problem is that a term was very likely wrong somewhere in the processing. E.g. if a CSV with headers and no meta.xml declare a column as `classs` it ends up as http://unknown.org/classs
