### ISSUE TITLE
-1 coordinate precision should not be interpreted as 1

### ISSUE THREAD

**Issue by cgendreau** [gbif/occurrence#9]
**-1 coordinate precision should not be interpreted as 1**

Should we not simply discard, rather than alter that?
Looking at the record diagnostic view, it seems &quot;-1&quot; is used for NULL

-----
fbitem-occurrence1135583752
Reported by: @timrobertson100
System: Chrome 55.0.2883 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/occurrence/1135583752
Window size: width 1721 - height 1099
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-07T18:30:42.473Z',mode:absolute,to:'2017-02-07T18:36:42.473Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-07T18:30:42.473Z',mode:absolute,to:'2017-02-07T18:36:42.473Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 38b4c89f-584c-41bb-bd8f-cd1def33e92f
publishingOrgKey: b8323864-602a-4a7d-9127-bb903054e97d

**Comment by cgendreau** [comment]
The reason is that we take the absolute value and check if it's between 0 and 45.

**Comment by timrobertson100** [comment]
That seems like a flawed algorithm to me - are there examples suggesting any negative value is trustworthy?  Would it not be better to err on the side of caution i.e. omit suspicious values rather than assert incorrect ones?

**Comment by cgendreau** [comment]
Are negative values are trustworthy? I don't know, maybe not, I would say it is probably handled that way in the sense of a ± "precision".
1 or -1 would mean 1 decimal degree of precision.

**Comment by timrobertson100** [comment]
The output of  ```hive> SELECT v_coordinateprecision, count(*) FROM prod_b.occurrence_hdfs GROUP BY v_coordinateprecision;``` is attached.  There is a lot of noise in this field and `41,523,350` records having `-1`.

I am not entirely sure what to do now, other than suggest the DwC documentation needs revision (CC @tucotuco who might be interest in this issue)

[v_coordinateprecision.txt](https://github.com/gbif/occurrence/files/758893/v_coordinateprecision.txt)

**Comment by tucotuco** [comment]
coordinatePrecision should be null or greater than zero, with only very few viable values. Anything else suggestion a misunderstanding of the concept.

Does this help?

https://github.com/tdwg/dwc-qa/issues/23

**Comment by cgendreau** [comment]
yes, thanks @tucotuco 
I think it would worth updating the [definition](http://rs.tdwg.org/dwc/terms/index.htm#coordinatePrecision) and/or have at least a reference to the very rich explanation included in https://github.com/tdwg/dwc-qa/issues/23

**Comment by tucotuco** [comment]
Interesting suggestion. The practical issue with changing Darwin Core term definitions is that it must pass through the onerous ratification process. Because of this a) definitions should be engineered to persist, and b) content, such as examples and comments, should not be a part of the definition that needs to be ratified. 

There is an [open proposal](https://github.com/tdwg/dwc/issues/26) to remove recommendations from the Darwin Core term definitions and put them into the comments. I don't see it documented, but the idea was also to have the comment separate from the normative definition, making it much easier to change with no ratification process. All of this awaits the ratification of the [TDWG Vocabulary Management standard](https://github.com/tdwg/vocab).

There is also an [open issue](https://github.com/tdwg/dwc/issues/82) to replace the GBIF Media Wiki method of supplementary material management. I believe the [Darwin Core Question and Answer wiki](https://github.com/tdwg/dwc-qa/wiki) to be a viable solution for that. I have opened an [issue to recover this documentation](https://github.com/VertNet/dwc-qa-manage/issues/9) to the Darwin Core Question and Answer wiki.
